"""Resume scoring report generator - runs evaluation prompts and saves markdown.

After the threshold is cleared and PDF is generated, this module:
1. Extracts text from the compiled PDF
2. Runs it through the technical recruiter evaluation prompts
3. Generates a detailed markdown report with scoring breakdown
4. Saves the report alongside the PDF in the output directory
"""
import logging
import subprocess
from pathlib import Path

from src.resume_scorer import score_resume, ScoringResult

log = logging.getLogger(__name__)

_SCORE_REPORT_MD_NAME = "resume_score_report.md"


def extract_pdf_text(pdf_path: str) -> str:
    """Extract text from PDF using pdftotext.

    Args:
        pdf_path: Path to the PDF file

    Returns:
        Extracted text content

    Raises:
        RuntimeError: If pdftotext fails or is not installed
    """
    try:
        result = subprocess.run(
            ["pdftotext", pdf_path, "-"],
            capture_output=True,
            text=True,
            check=True,
            timeout=30,
        )
        return result.stdout
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"pdftotext failed: {e.stderr}") from e
    except subprocess.TimeoutExpired as e:
        raise RuntimeError("pdftotext timed out after 30s") from e
    except FileNotFoundError as e:
        raise RuntimeError(
            "pdftotext not found - install poppler-utils (brew install poppler)"
        ) from e


def format_markdown_report(result: ScoringResult) -> str:
    """Format the scoring result as a clean markdown report.

    Args:
        result: ScoringResult with all scoring data

    Returns:
        Formatted markdown string
    """
    data = result.to_dict()

    # Build category breakdown table
    category_rows = []
    for category, details in data["category_scores"].items():
        category_name = category.replace("_", " ").title()
        score = details["score"]
        max_score = details["max"]
        category_rows.append(f"| {category_name:<20} | {score:>3}/{max_score:<3} |")

    # Build key strengths list
    strengths_md = "\n".join(f"{i}. {s}" for i, s in enumerate(data["key_strengths"], 1))

    # Build areas for improvement list
    improvements_md = "\n".join(f"{i}. {a}" for i, a in enumerate(data["areas_for_improvement"], 1))

    # Build evidence breakdown
    evidence_sections = []
    for category, details in data["category_scores"].items():
        category_name = category.replace("_", " ").title()
        evidence_sections.append(
            f"### {category_name} ({details['score']}/{details['max']})\n\n"
            f"{details['evidence']}\n"
        )

    markdown = f"""# Resume Scoring Report

**Generated by resume-bot evaluation engine**

---

## Executive Summary

| Metric | Score |
|--------|-------|
| **Final Score** | **{data['final_score']}/120** |
| Category Total | {data['category_total']}/100 |
| Bonus Points | +{data['bonus_points']['total']} |
| Deductions | -{data['deductions']['total']} |

---

## Category Breakdown

| Category | Score |
|----------|-------|
{chr(10).join(category_rows)}

---

## Bonus Points (+{data['bonus_points']['total']})

{data['bonus_points']['breakdown']}

---

## Deductions (-{data['deductions']['total']})

{data['deductions']['reasons']}

---

## Key Strengths

{strengths_md}

---

## Areas for Improvement

{improvements_md}

---

## Detailed Evidence

{chr(10).join(evidence_sections)}

---

## Scoring Methodology

This resume was evaluated using a comprehensive technical recruiter assessment framework:

### Scoring Categories

1. **Self Projects (0-50 points)**: Personal project complexity, real-world impact, live demos, architecture quality
2. **Production (0-40 points)**: Professional work experience, production-level contributions, startup/early-stage involvement
3. **Technical Skills (0-10 points)**: Programming languages, frameworks, tools, breadth and depth of technical expertise

### Bonus Points (max 20)
- Portfolio/live demos
- LinkedIn profiles with strong presence
- Technical blogs
- Startup founder/co-founder experience
- Early-stage engineer experience
- Relevant certifications (AWS, GCP, etc.)

### Deductions
- Simple/tutorial projects without complexity
- Missing project links or demos
- Broken or inactive project URLs
- Lack of verifiable contributions

### Fairness Guarantees

**Scores are based ONLY on:**
- Technical skills and demonstrated expertise
- Project complexity and real-world impact
- Professional experience and contributions
- Live demos and deployed applications

**Scores NEVER depend on:**
- Personal demographic information
- Educational institution names or prestige
- GPA or academic grades
- Geographic location

---
"""
    return markdown


def generate_score_report(pdf_path: str, out_dir: str) -> str:
    """Generate markdown scoring report for the compiled resume PDF.

    Args:
        pdf_path: Path to the compiled PDF resume
        out_dir: Output directory where report will be saved

    Returns:
        Path to the saved markdown report

    Raises:
        RuntimeError: If PDF text extraction or scoring fails
    """
    log.info("score_report | extracting text from %s", pdf_path)

    try:
        resume_text = extract_pdf_text(pdf_path)
    except RuntimeError as e:
        log.error("score_report | PDF text extraction failed: %s", e)
        raise

    log.info("score_report | running LLM evaluation (30-60s)...")

    try:
        result = score_resume(resume_text)
    except Exception as e:
        log.error("score_report | LLM scoring failed: %s", e)
        raise RuntimeError(f"Resume scoring failed: {e}") from e

    log.info("score_report | final score: %d/120", result.final_score)

    # Format and save markdown report
    markdown_content = format_markdown_report(result)

    out_path = Path(out_dir) / _SCORE_REPORT_MD_NAME
    out_path.write_text(markdown_content, encoding="utf-8")

    log.info("score_report | markdown report → %s", out_path)

    return str(out_path)


def score_report_node(state: dict) -> dict:
    """Graph node: generate scoring report after PDF emission.

    Only runs if a PDF was successfully emitted. Failures are logged but
    do not crash the pipeline - the score report is a nice-to-have, not
    a requirement.

    Args:
        state: Pipeline state containing output_pdf and out_dir

    Returns:
        Dict with score_report_md path (or None if scoring failed)
    """
    pdf_path = state.get("output_pdf")
    if not pdf_path:
        log.warning("score_report | no PDF found - skipping scoring")
        return {"score_report_md": None}

    out_dir = state.get("out_dir", "out")

    try:
        report_path = generate_score_report(pdf_path, out_dir)
        return {"score_report_md": report_path}
    except Exception as e:
        log.error("score_report | failed to generate scoring report: %s", e, exc_info=True)
        # Don't crash the pipeline - just return None
        return {"score_report_md": None}
