"""PipelineState — the shared TypedDict flowing through the LangGraph.

``total=False`` so partial states are valid: each node fills in the fields for
its lifecycle stage without needing to populate the whole dict.
"""
from typing import TypedDict

from src.pipeline.schemas import (
    IdentityLedger,
    JDVector,
    PanelScore,
    ReframingTarget,
    ResumeStruct,
    SkillDump,
    WriterOutput,
)


class PipelineState(TypedDict, total=False):
    """State passed between pipeline nodes, grouped by lifecycle stage."""

    # --- inputs ---------------------------------------------------------------
    resume_tex_raw: str
    jd_raw: str
    enable_scoring: bool

    # --- extraction -----------------------------------------------------------
    resume_struct: ResumeStruct
    identity_ledger: IdentityLedger
    jd_vector: JDVector
    gap_targets: list[ReframingTarget]

    # --- writer ---------------------------------------------------------------
    writer_output: WriterOutput
    latex_rendered: str

    # --- compile --------------------------------------------------------------
    compile_ok: bool
    compile_errors: str

    # --- eval -----------------------------------------------------------------
    panel_scores: list[PanelScore]
    # Exact-match memoization for the recruiter panel: the rendered LaTeX last
    # scored, and the scores it produced. When a later iteration's
    # latex_rendered is byte-identical (the writer converged/plateaued),
    # recruiter_panel reuses these instead of re-running all four persona
    # calls. MUST be declared here — LangGraph silently drops updates to
    # channels absent from this schema (see length_violations history above).
    panel_cache_latex: str
    panel_cache_scores: list[PanelScore]
    aggregate_score: float
    passed: bool
    # Ranked revision directives distilled by the aggregator.
    revision_notes: list[str]

    # --- length gate ----------------------------------------------------------
    # Recorded by ``check_bullet_lengths``; a non-empty list routes back to the
    # writer (within the length-retry budget). Absent/empty means every bullet
    # is in-band. MUST be declared here — LangGraph silently drops updates to
    # channels that are not part of the state schema, which would make the gate
    # a no-op.
    length_violations: list[str]
    # Per-iteration length-retry counter. Reset in ``bookkeep_node`` alongside
    # ``compile_retries`` so each revision iteration gets a fresh budget.
    length_retries: int

    # --- compile-loop / identity bookkeeping ----------------------------------
    # Recorded by ``identity_check_node``; a non-empty list routes back to the
    # writer. Absent/empty means the render is clean.
    identity_violations: list[str]
    # Per-iteration compile-retry counter, separate from ``iteration`` so a
    # compile bounce never consumes a revision iteration.
    compile_retries: int
    # Global identity-retry counter. Incremented each time identity_check_node
    # detects violations; NOT reset on clean passes (global budget, not per-iter).
    identity_retries: int

    # --- skills (generated once, before the writer loop) ---------------------
    # Produced by ``generate_skills`` and stable across all revision iterations.
    # MUST be declared here — LangGraph silently drops updates to channels absent
    # from the state schema.
    skill_dump: SkillDump

    # --- bookkeeping ----------------------------------------------------------
    iteration: int
    best_score: float
    best_latex: str
    # PDF path corresponding to the best-scoring draft. Tracked alongside
    # best_latex so emit can copy the correct file even after later iterations
    # overwrite pdf_path.
    best_pdf_path: str
    pdf_path: str

    # --- emit -----------------------------------------------------------------
    # True when the loop terminated by hitting MAX_ITERATIONS without passing;
    # the emitter surfaces the best-scoring draft with a warning.
    cap_hit: bool
    # Set by the emit node once outputs are written (terminal signal + paths).
    emitted: bool
    output_pdf: str
    output_report: str
    # Seeded by the CLI so the emit node knows where to write.
    out_dir: str
    # Stem of the JD file path (e.g. "amazon_sde" from "examples/amazon_sde.txt").
    # Used by emit to name the output PDF after the JD.
    jd_name: str
    # Markdown scoring report generated by score_report_node after PDF emission.
    score_report_md: str | None
